version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: blog_api_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret9009
      POSTGRES_DB: blog_api
    ports:
      - "5433:5432"
    volumes:
      - blog_api_data:/var/lib/postgresql/data

volumes:
  blog_api_data:
